services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./workflow/Dockerfile
    autoDeploy: true
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_PORT
        value: 5678
